ncc-erp/ncc-erp-ams

- .github/workflows/action-tests.yml
- Fix Action Test To Run Unit Test
> Fix Action Test To Run Unit Test

- .github/workflows/action-tests.yml
- Update Github Action trigger for PR workflow
> Update Github Action trigger for PR workflow

- tests/api/ApiSoftwareCest.php
#50029 Coverage Test Api Software Controller
- Evidence: https://drive.google.com/file/d/1hzgzedlIhp3Kgb8moiFjIBqPS3YhHq0o/view?usp=sharing
> #50029: Coverage Test Api Software Controller

- routes/api.php
- tests/api/ApiStatusLabelsCest.php
Task 50031: https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/50031
Update ApiStatusLabelsCest
Update missing id in status labels api
Evidence: https://drive.google.com/file/d/1oTRhJtam57hdNW7VX0ucwY6TEuq1tNGN/view?usp=sharing
> #50031: coverage test status labels controller

- tests/api/ApiDashboardCest.php
#50012 Coverage Api Test DashboardController
Evidence: https://drive.google.com/file/d/1Hty3KRKC9E8x7BJnF5vJFiPVGPWHeEMi/view?usp=sharing
> #50012: Coverage Api Test DashboardController

- tests/api/ApiDashboardCest.php
- tests/api/ApiReportCest.php
#50027: Coverage Test Api Report Controller
Evidence: https://drive.google.com/file/d/11rziU3mjAYwXteNXz4DddIQlmmsSP-rp/view?usp=sharing
> #50027: Coverage Test Api Report

- tests/api/ApiLocationsCest.php
Task 50607: https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/50607
Update ApiStatusLabelsCest
Update missing id in status labels api
Evidence: https://drive.google.com/file/d/1XX1QG4g62KnB6ttIR8dSg9F5LD74-1m2/view?usp=sharing
> Update LocationsCest for coverage test #50607

- app/Http/Controllers/Api/AccessoriesController.php
- app/Http/Controllers/Api/AssetsController.php
- app/Http/Controllers/Api/ConsumablesController.php
- app/Http/Controllers/Api/DigitalSignaturesController.php
- app/Http/Controllers/Api/ReportsController.php
- app/Http/Controllers/Api/ToolController.php
- routes/api.php
- tests/api/ApiAccessoriesCest.php
- tests/api/ApiAssetsCest.php
- tests/api/ApiConsumablesCest.php
- tests/api/ApiDigitalSignaturesCest.php
- tests/api/ApiReportCest.php
- tests/api/ApiToolCest.php
Task 50851: https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/50851
Evidence: https://www.loom.com/share/f5f3da26cc804cc584d74a71a0a28615
> #50851: Add total detail api & update api test 

- app/Http/Controllers/Api/UsersController.php
- app/Models/User.php
> Hot fix assign asset to user

- app/Http/Controllers/Api/CategoriesController.php
- app/Http/Transformers/CategoriesTransformer.php
- app/Models/Category.php
- Task : https://ops.nccsoft.vn/DefaultCollection/NCC-ITTools/_workitems/edit/51595
- Evidence: https://www.loom.com/share/7ddcc02d73764a538abaf96c54c55e3a
> #51595: Fix Tool display 

- tests/api/ApiAccessoriesCest.php
- tests/api/ApiCategoriesCest.php
- tests/api/ApiCompaniesCest.php
- tests/api/ApiComponentsCest.php
- tests/api/ApiConsumablesCest.php
- tests/api/ApiDigitalSignaturesCest.php
- tests/api/ApiLicensesCest.php
- tests/api/ApiLocationsCest.php
- tests/api/ApiManufacturersCest.php
- tests/api/ApiModelsCest.php
- tests/api/ApiStatusLabelsCest.php
- tests/api/ApiToolCest.php
- tests/api/ApiUsersCest.php
> Fix Api Test

- .github/workflows/docker-deploy-dev.yml
> fix: skip test fail for build app

- .github/workflows/docker-deploy-dev.yml
> fix: skip test part

- app/Console/Commands/SendMaintenanceNotifications.php
- app/Console/Kernel.php
- app/Http/Controllers/Api/AccessoriesController.php
- app/Http/Controllers/Api/AssetsController.php
- app/Http/Controllers/Api/ClientAssetsController.php
- app/Http/Controllers/Api/ConsumablesController.php
- app/Http/Controllers/Api/DigitalSignaturesController.php
- app/Http/Controllers/Api/ToolController.php
- app/Http/Controllers/Api/WebhookController.php
- app/Http/Transformers/AssetsTransformer.php
- app/Http/Transformers/ConsumablesTransformer.php
- app/Http/Transformers/WebhookTransformer.php
- app/Models/Asset.php
- app/Models/Consumable.php
- app/Models/Webhook.php
- app/Models/WebhookLog.php
- database/factories/WebhookFactory.php
- database/migrations/2025_06_12_030244_create_webhooks_table.php
- database/migrations/2025_06_12_073313_add_webhook_id_to_assets_table.php
- database/migrations/2025_06_12_084750_alter_url_length_in_webhooks_table.php
- database/migrations/2025_06_13_063736_add_type_to_webhooks_table.php
- database/migrations/2025_06_13_071059_create_webhook_logs_table.php
- database/migrations/2025_06_18_071346_add_webhook_id_to_consumables_table.php
- database/seeders/WebhookSeeder.php
- resources/lang/en/admin/webhook/message.php
- resources/lang/vi/admin/webhook/message.php
- routes/api.php
- tests/api/ApiWebhookCest.php
- Add Mezon webhook support for admin
- https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/360
- https://www.awesomescreenshot.com/video/40923699?key=5a1b568a3b8db863b7698e6bb7506744
- https://www.awesomescreenshot.com/video/41093789?key=99566b39eb1c833aea3235badfed8a51
- https://www.awesomescreenshot.com/video/41167617?key=f06c2b906928c97d208d8e09173fd231
> Add Mezon webhook support for admin

- .github/workflows/docker-deploy-dev.yml
> feat: update workflow for migration

- app/Http/Controllers/Api/AssetsController.php
- routes/api.php
Add getCustomerRentingAssets api for assets
Add getCustomerRentingAssetsTotalDetail api for assets
Add isCustomerRenting field for asset update
I tested function with postman
*Evidence:
* PHP version:
* OS version
> feat(112): customer renting feature

- app/Http/Controllers/Api/AssetsController.php
- app/Http/Transformers/AssetsTransformer.php
- app/Models/Asset.php
- database/migrations/2025_07_29_040837_add_start_rental_date_to_assets_table.php
- Komu Logs UI for Admin
- #100
-https://www.awesomescreenshot.com/video/42546358?key=898750ae863e321c36b5decbb3a758fb
> feat(AMS-112): fix filter date and add input ngay khach hang thue

- app/Console/Commands/SendMaintenanceNotifications.php
- app/Http/Controllers/Api/AccessoriesController.php
- app/Http/Controllers/Api/AssetsController.php
- app/Http/Controllers/Api/ClientAssetsController.php
- app/Http/Controllers/Api/ConsumablesController.php
- app/Http/Controllers/Api/DigitalSignaturesController.php
- app/Http/Controllers/Api/KomuLogsController.php
- app/Http/Controllers/Api/ToolController.php
- app/Http/Controllers/Api/WebhookLogsController.php
- app/Http/Transformers/KomuLogsTransformer.php
- app/Http/Transformers/WebhookLogsTransformer.php
- app/Models/KomuMessageLog.php
- app/Models/WebhookLog.php
- database/factories/KomuMessageLogFactory.php
- database/factories/WebhookLogFactory.php
- database/migrations/2025_06_30_061315_update_webhook_logs_columns.php
- database/migrations/2025_06_30_062440_update_type_of_message__columns.php
- database/migrations/2025_06_30_062616_update_type_of_asset__columns.php
- database/migrations/2025_06_30_065331_add_webhooks_type_column.php
- database/migrations/2025_07_01_021038_alter_webhook_id_type_in_webhook_logs_table.php
- resources/lang/vi/admin/komu_logs/message.php
- resources/lang/vi/admin/webhook_logs/message.php
- routes/api.php
- tests/api/ApiKomuLogsCest.php
- tests/api/ApiWebhookLogsCest.php
- Komu Logs UI for Admin
- https://github.com/ncc-erp/ncc-erp-ams-fe/issues/88
- https://www.awesomescreenshot.com/video/41431507?key=fbadeffa1113dc3af0dd7fcbd42c1dad
> Komu Logs UI for Admin

- app/Http/Controllers/Api/AssetsController.php
- app/Models/Asset.php
Add customer-renting fields in asset checkout
Tested by FE
* PHP version:
* OS version
> feat(AMS): set up customer-renting in asset checkout

- SETUP.md
- code-guidelines.md
- create SETUP.md and code-guidelines.md
- #130
> feat(AMS-130): create setup.md and code-guidelines.md

- app/Http/Controllers/Api/AssetsController.php
- app/Jobs/SendConfirmMail.php
- app/Jobs/SendRejectAllocateMail.php
- app/Services/KomuService.php
- app/Services/MailService.php
> hotfix: fix komu send wrong username when issue or invoke hardware

- .github/workflows/deploy-prod.yml
- .gitignore
> feat(AMS-34): prod ci/cd

- .github/workflows/deploy-prod.yml
- .gitignore
> Merge Dev to Master

- .github/workflows/deploy-prod.yml
> fix(AMS-34): remove laravel caches config

- .env.example
- app/Http/Controllers/Api/AccessoriesController.php
- app/Http/Controllers/Api/AssetsController.php
- app/Jobs/SendCheckinMail.php
- app/Jobs/SendCheckinMailDigitalSignature.php
- app/Jobs/SendCheckinMailTool.php
- app/Jobs/SendCheckoutMail.php
- app/Jobs/SendCheckoutMailDigitalSignature.php
- app/Jobs/SendCheckoutMailSoftware.php
- app/Jobs/SendCheckoutMailTool.php
- app/Jobs/SendConfirmCheckinMail.php
- app/Jobs/SendConfirmCheckoutMail.php
- app/Jobs/SendConfirmMail.php
- app/Jobs/SendConfirmMailTool.php
- app/Jobs/SendConfirmRevokeMail.php
- app/Jobs/SendRejectAllocateMail.php
- app/Jobs/SendRejectCheckinMail.php
- app/Jobs/SendRejectCheckoutMail.php
- app/Jobs/SendRejectRevokeMail.php
- app/Services/KomuService.php
- config/admin.php
* PHP version:
* OS version
SendConfirmMail.php
SendRejectAllocateMail.php
SendConfirmRevokeMail.php
SendRejectRevokeMail.php
SendConfirmMailTool.php
SendConfirmCheckoutMail.php
SendRejectCheckoutMail.php
SendConfirmCheckinMail.php
SendRejectCheckinMail.php
> feat(AMS-183): fix komu send wrong username format

- .env.example
- .github/workflows/deploy-prod.yml
- .gitignore
- app/Http/Controllers/Api/AssetsController.php
- app/Jobs/SendCheckinMail.php
- app/Jobs/SendCheckinMailDigitalSignature.php
- app/Jobs/SendCheckinMailTool.php
- app/Jobs/SendCheckoutMail.php
- app/Jobs/SendCheckoutMailDigitalSignature.php
- app/Jobs/SendCheckoutMailSoftware.php
- app/Jobs/SendCheckoutMailTool.php
- app/Jobs/SendConfirmCheckinMail.php
- app/Jobs/SendConfirmCheckoutMail.php
- app/Jobs/SendConfirmMail.php
- app/Jobs/SendConfirmMailTool.php
- app/Jobs/SendConfirmRevokeMail.php
- app/Jobs/SendRejectAllocateMail.php
- app/Jobs/SendRejectCheckinMail.php
- app/Jobs/SendRejectCheckoutMail.php
- app/Jobs/SendRejectRevokeMail.php
- app/Services/KomuService.php
- config/admin.php
> Merge Develop to Master

- app/Models/Tool.php
- app/Repositories/ToolRepository.php
In my domain/tool page, when send query search to server, it will send Internal Server Error, the Laravel Log show PDO query error.
Fixes # (issue) #195
Fix alias of query.
* PHP version:
* OS version
https://www.awesomescreenshot.com/video/44305868?key=49fc667c69747c0b1248095ddd592c2d
> fix(AMS-195): fix tool domain search issue

- app/Http/Controllers/Api/LocationsController.php
> hotfix(AMS): sort location by asc
